config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :users do
    member do
     get :likes 
    end
  end
  
  resources :recipes
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { maximum: 30 }
    validates :material, presence: true
    validates :cooking_time, presence: true, length: { maximum: 30 }
    validates :process, presence: true
    mount_uploader :image, ImageUploader
    
    has_many :favorites
    has_many :users, through: :favorites
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    mount_uploader :image, ImageUploader
    has_secure_password
    
    has_many :recipes
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :favorites
    has_many :fav_recipes, through: :favorites, source: :recipe

    def follow(other_user)
     unless self == other_user
        self.relationships.find_or_create_by(follow_id: other_user.id)
     end
    end

    def unfollow(other_user)
     relationship = self.relationships.find_by(follow_id: other_user.id)
     relationship.destroy if relationship
    end

    def following?(other_user)
     self.followings.include?(other_user)
    end
    
    def feed_recipes
     Recipe.where(user_id: self.following_ids + [self.id])
    end
    
    def favorite(recipe)
     self.favorites.find_or_create_by(recipe_id: recipe.id)
    end
  
    def unfavorite(recipe)
     favorite = self.favorites.find_by(recipe_id: recipe.id)
     favorite.destroy if favorite
    end
    
    def favorite?(recipe)
     self.fav_recipes.include?(recipe)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_recipes = user.recipes.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_likes = user.fav_recipes.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    recipe = Recipe.find(params[:recipe_id])
    current_user.favorite(recipe)
    flash[:success] = 'レシピを「お気に入り」に保存しました！'
    redirect_to recipe_path(recipe) 
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    current_user.unfavorite(recipe)
    flash[:success] = 'レシピを「お気に入り」から削除しました'
    redirect_to recipe_path(recipe) 
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_user_logged_in, only: [:update, :create, :edit, :destroy]
  before_action :correct_user, only: [:update, :edit, :destroy]
  def index
    if logged_in?
      @recipes = Recipe.all.order(id: :desc)
      @frecipes = current_user.feed_recipes.order(id: :desc).page(params[:page])
    else
      @recipes = Recipe.all.order(id: :desc)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = 'レシピを投稿しました！'
      redirect_to root_url
    else
      @recipes = Recipe.all
      @frecipes = current_user.feed_recipes.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'レシピの投稿に失敗しました'
      render :new
    end
  end
  
  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      flash[:success] = 'レシピを更新しました'
      redirect_to @recipe
    else
      flash.now[:danger] = 'レシピの更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = 'レシピを削除しました'
    redirect_to root_url
  end
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:title, :material, :image, :cooking_time, :process, :comment)
  end
  
  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    unless @recipe
      redirect_to root_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'フォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'フォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :correct_user, only: [:update, :edit, :destroy]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes.order(id: :desc).page(params[:page])
    @followings = @user.followings.page(params[:page])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'ユーザー登録が完了しました！'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     redirect_to @user
   else
    render :edit
   end
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.fav_recipes.page(params[:page])
    counts(@user)
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
  def follow_user
    @follow_user = @user.all_following
  end 
  
  def current_user?(user)
    user == current_user
  end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(recipe) %>
    <%= form_with(model: current_user.favorites.find_by(recipe_id: recipe.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :recipe_id, recipe.id %>
      <%= button_tag type: 'submit', class: 'btn btn-sm btn-block fav' do %>
        <i class="fas fa-heart"></i>
      <% end %>
    <% end %>
<% else %>
    <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
      <%= hidden_field_tag :recipe_id, recipe.id %>
      <%= button_tag type: 'submit', class: 'btn btn-sm btn-block' do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4 ">
  <nav class="navbar navbar-expand-sm header">
    <a class="title wf-roundedmplus1c" href="/">おひとりさま食堂</a>
    <div class="text wf-roundedmplus1c">
      <p>一人暮らし専用レシピ投稿サービス</p>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="header-tab wf-roundedmplus1c dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user), class: 'wf-sawarabigothic nav-item' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'お気に入りレシピ', likes_user_path(current_user), class: 'wf-sawarabigothic nav-item' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'レシピを書く', new_recipe_path(current_user), class: 'wf-sawarabigothic nav-item' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'wf-sawarabigothic nav-item' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '会員登録', signup_path, class: 'wf-roundedmplus1c header-tab left-tab' %></li>
          <li><%= link_to 'ログイン', login_path, class: 'wf-roundedmplus1c header-tab' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>おひとりさま食堂</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @recipe, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :title, 'レシピ名' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :comment, 'レシピへのコメント' %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, '完成写真' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :cooking_time, '調理時間' %>
        <%= f.text_field :cooking_time, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :material, '材料と分量' %>
        <%= f.text_area :material, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :process, '作り方' %>
        <%= f.text_area :process, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>
  

app/views/recipes/_recipe.html.erb
<div class="row">
 <% recipes.each do |recipe| %>
  <div class="col-md-4">
   <div>
    <% if recipe.image? %>
      <img  class="mr-2 rounded" src='<%= recipe.image %>' width="200" hight="200">
    <% else %>
      <%= image_tag "default_cooking.png", width:200, hight:200 %>
    <% end %>
    <br>
    <h4><%= link_to recipe.title, recipe_path(recipe), class: "wf-sawarabigothic recipe-title" %></h4>
    <p class="wf-sawarabigothic recipe-item">by：<%= link_to recipe.user.name, user_path(recipe.user), class: 'wf-sawarabigothic recipe-item' %></p>        
    <p class="wf-sawarabigothic recipe-item">調理時間：<%= recipe.cooking_time %></p>
   </div>
  </div>
 <% end %>
</div>

app/views/recipes/edit.html.erb
<div class="text-center">
  <h1>レシピの編集</h1>
</div>
<%= render 'recipes/form', recipe: @recipe %>

app/views/recipes/index.html.erb
<% if logged_in? %>
<div class="col-sm-12">
　<ul class="nav nav-tabs nav-justified mb-3">
    <li class="nav-item">
        <a href="#all_recipes" class="nav-link active wf-sawarabigothic" data-toggle="tab" >みんなのレシピ</a>
    </li>
    <li class="nav-item">
        <a href="#follow_recipes" class="nav-link wf-sawarabigothic" data-toggle="tab" >フォローしている人のレシピ</a>
    </li>
　</ul>
</div>

<div class="tab-content">
    <div id="all_recipes" class="tab-pane active">
      <%= render 'recipes/recipe', recipes: @recipes %>
    </div>
    <div id="follow_recipes" class="tab-pane">
      <%= render 'recipes/recipe', recipes: @frecipes %>
    </div>
</div>
<% else %>
<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3">
    <li class="nav-item">
        <a href="#all_recipes" class="nav-link active wf-sawarabigothic" data-toggle="tab" >みんなのレシピ</a>
    </li>
  </ul>
</div>
<div class="tab-content">
  <div id="all_recipes" class="tab-pane active">
    <%= render 'recipes/recipe', recipes: @recipes %>
  </div>
</div>
<% end %>

app/views/recipes/new.html.erb
<div class="text-center">
  <h1>レシピの投稿</h1>
</div>
<%= render 'recipes/form', recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="recipe-top">
  <div class="recipe-title wf-sawarabigothic">
      <h1><%= @recipe.title %></h1>
  </div>
  <div class="my-btn">
    <div class="dl-btn">
      <% if current_user == @recipe.user %>
        <%= link_to (@recipe), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn btn-sm' do %>
          <i class="fas fa-trash-alt"></i>
        <% end%>
      <% end%>
    </div>
    <div class="ed-btn">
      <% if current_user == @recipe.user %>
        <a href="<%= edit_recipe_path(@recipe) %>" class="btn btn-sm ed-btn"><i class="fas fa-edit"></i></a>
      <% end %>
    </div>
    <div>
      <% if logged_in? %>
        <%= render 'favorites/favorite_button', recipe: @recipe %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
<div class="col-sm-4 recipe-left wf-sawarabigothic">
  <div class="recipe_image">
    <% if @recipe.image? %>
      <img  class="mr-2 rounded" src='<%= @recipe.image %>' width="350" hight="350">
    <% else %>
      <%= image_tag "default_cooking.png", width:350, hight:350 %>
    <% end %>
  </div>
  <div class="recipe-comment">
    <p><%= @recipe.comment %></p>
  </div>
  <div>
    <p>調理時間：<%= @recipe.cooking_time %></p>
  </div>
</div>
<div class="col-sm-4 recipe-center wf-sawarabigothic">
  <div>
    <h3>材料</h3><br>
    <p><%= @recipe.material %></p>
  </div>
</div>
<div class="col-sm-4 recipe-right wf-sawarabigothic">
  <div>
    <h3>作り方</h3><br>
    <p><%= @recipe.process %></p>
  </div>  
</div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= button_tag type: 'submit', class: 'btn btn-sm btn-block unf-btn' do %>
        <p><i class="fas fa-user"></i>フォロー中</p>
      <% end %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= button_tag type: 'submit', class: 'btn btn-sm btn-block f-btn' do %>
        <p><i class="fas fa-user-plus"></i>フォローする</p>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_followers.html.erb
<% if followers.any? %>
  <ul class="list-unstyled">
    <% followers.each do |user| %>
      <li class="media">
        <% if user.image? %>
            <img src="<%= user.image %>" width="50" hight="50">
        <% else %>
            <%= image_tag "default.png", width:50, hight:50 %>
        <% end %> 
        <div class="media-body">
          <div class="followers">
            <p><%= link_to user.name, user_path(user), class: "wf-sawarabigothic" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate followers %>
<% end %>

app/views/users/_followings.html.erb
<% if followings.any? %>
  <ul class="list-unstyled">
    <% followings.each do |user| %>
      <li class="media">
        <% if user.image? %>
            <img src="<%= user.image %>" width="50" hight="50">
        <% else %>
            <%= image_tag "default.png", width:50, hight:50 %>
        <% end %> 
        <div class="media-body">
          <div class="followings">
            <p><%= link_to user.name, user_path(user), class: "wf-sawarabigothic" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate followings %>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザー名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, 'プロフィール画像' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-block register-btn' %>
    <% end %>
  </div>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <p><%= link_to user.name, user_path(user), class: "wf-sawarabigothic recipe-title" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>プロフィール編集</h1>
</div>
<%= render 'users/form', user: @user %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="col-sm-12">
  <ul class="nav nav-tabs nav-justified mb-3">
    <li class="nav-item">
        <a href="#all_recipes" class="nav-link active wf-sawarabigothic" data-toggle="tab" >お気に入りレシピ <span class="badge badge-secondary"><%= @count_likes %></span></a>
    </li>
  </ul>
</div>
<div class="tab-content">
  <div id="all_recipes" class="tab-pane active">
    <%= render 'recipes/recipe', recipes: @likes %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>会員登録</h1>
</div>

<%= render 'users/form', user: @user %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title wf-sawarabigothic"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <% if @user.image? %>
            <img src="<%= @user.image %>" width="300" hight="300">
        <% else %>
            <%= image_tag "default.png", width:300, hight:300 %>
        <% end %>  
      </div>
    </div>
    <br>
    <div>
      <% if current_user.id == @user.id %>
        <a href="<%= edit_user_path(@user) %>" class="btn btn-sm btn-block"><p class="edit-btn"><i class="fas fa-user-edit"></i>プロフィールを編集する</p></a>
      <% end %>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item">
        <a href="#myrecipes" class="nav-link active wf-sawarabigothic" data-toggle="tab" >投稿レシピ一覧 <span class="badge badge-secondary"><%= @count_recipes %></span></a>
      </li>
      <li class="nav-item">
        <a href="#followings" class="nav-link wf-sawarabigothic" data-toggle="tab" >フォロー<span class="badge badge-secondary"><%= @count_followings %></span></a>
      </li>
      <li class="nav-item">
        <a href="#followers" class="nav-link wf-sawarabigothic" data-toggle="tab" >フォロワー<span class="badge badge-secondary"><%= @count_followers %></span></a>
      </li>
　  </ul>
　  <div class="tab-content">
      <div id="myrecipes" class="tab-pane active">
        <%= render 'recipes/recipe', recipes: @recipes %>
      </div>
      <div id="followings" class="tab-pane">
        <%= render 'users/followings', followings: @followings %>
      </div>
      <div id="followers" class="tab-pane">
        <%= render 'users/followers', followers: @followers %>
      </div>
    </div>
  </div>
</div>